### PR TITLE
Minor update for new grails/gorm/hibernate

### PR DESCRIPTION
**Pull request by Omasiri**

### CODE REVIEW

**Comment by ejaz-ahmed** [comment]
@Omasiri which version of hibernate/grails your PR refers too? I get following errors for grails 3.0.x and hibernate 4

```
/home/ejaz/github/grails-multitenant-plugin/multitenant/src/main/groovy/org/grails/plugin/multitenant/HibernateMultitenantConfiguration.groovy: 6: unable to resolve class org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration
 @ line 6, column 1.
   import org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration
   ^

1 error

:multitenant:compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':multitenant:compileGroovy'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Can you provide little bit more explanation of your change sets?

**Comment by ejaz-ahmed** [comment]
It that for grails 3.1 and hibernate 5?

**Comment by Omasiri** [comment]
@ejaz-ahmed ,
It is for grails 3.1.1 and hibernate 5. 

Thanks.

**Comment by ejaz-ahmed** [comment]
Thanks for the contribution. I'll create a separate branch for for old 3.0.x first and merge your PR in master. Current master will be for grails 3.1 then. I noticed this failure of this plugin for grails 3.1 and hibernate 4 but could not find time to investigate. Will into it as well and probably find some time write automated tests too.

**Comment by ejaz-ahmed** [comment]
@Omasiri while your changes seem to be valid as per GORM5 documentation but I am unable to test this. Your changes even fail to  compile on grails 3.0.11 and grails 3.1.1. Can you please explain how did you validated your changes? Can you share working application along with the plugin?

**Comment by Omasiri** [comment]
@ejaz-ahmed. I made the changes for Gorm5 and grails 3.1.1.

**Comment by Omasiri** [comment]
I have compiled and installed this plugin on my local cache. (new PR ) I used the example application inside the plugin project folder to check the plugin. Please download https://github.com/Omasiri/grails-multitenant-plugin and verify.

**Comment by ejaz-ahmed** [comment]
[diff.txt](https://github.com/ejaz-ahmed/grails-multitenant-plugin/files/154420/diff.txt)

@Omasiri this app does not produce the required results. I've attached patch for your repo. Apply this patch and see the results. Login with username:her and password:her. You will see books of both tenantIds (1 and 2) which is not the expected output. Hibernate filter is not being applied properly. CRUD operations and tenantResolverService is working properly. You are using hibernate4 in your application where as plugin is being compiled for hibernate5. This might also be the problem. If I change to hibernate5 in application, build fails.

**Comment by Omasiri** [comment]
@ejaz-ahmed : you are correct. I was going to bring it up after we sorted out the non compile issue. 
I experienced the issue when I tried to use it for a demo app.

**Comment by ejaz-ahmed** [comment]
@Omasiri got your point. Merging it to master branch. Now I've three branches. One is for grails 3.0.x hibernate4 (the only working branch), another is for grails 3.1 and hibernate4. Master branch is for grails 3.1 and hibernate 5. Hibernate filter logic in the plugin is based on hibernate 4 and I've not yet looked into hibernate 5. It might be easier for your to use hibernate 4 first so that the plugin is at least functional for grails 3.1 which uses hibernate 4 as default version of hibernate. If you go this way, then use grails 3.1 and hibernate 4 branch instead of master. I am merging your changes in master and adding changes in the patch file too plus some automated tests in sample application.

**Comment by ejaz-ahmed** [comment]
@Omasiri have you time to look into remaining section of your PR? I am rolling in another feature probably next week which is domain name based tenant resolver.

**Comment by Omasiri** [comment]
@ejaz-ahmed I have created the branches. The only working branch ( like you said) is the 3.0.x version. The 3.1.x hibernate4 does not produce the desired result. I don't know why but I will try to explore solutions for it and the 3.1.x hibernate5 version soon.
